### ISSUE TITLE
epoll_wait causes high CPU usage

### ISSUE THREAD

**Issue by nijinboc** [Mellanox/libvma#33] opened 2015-10-09 21:10 UTC
Hi,

This issue has been puzzled me for a while.
Every time using libvma, the CPU usage becomes high when client doing disconnect and reconnect.
I checked gstack, seems epoll_wait becomes nonblock and keeps looping.

When not using libvma, TCP's recv seems not having such issue.

**Comment by rosenbaumalex** [comment] 2015-10-14 14:32
By design VMA is tuned to push each user application thread which is calling a socket receive API and this drives the VMA engine handle all packets. The lower latency is achieved by keeping this thread spinning on the HW until an ingress packet is received and then handling it in VMA.

This 'spinning' module is the default VMA configuration. You can turn off the high polling configuration but you'll loss the very good low latency performance.

The socket 'receive' APIs which push the Rx polling include: 
- recv() recvfrom(), recvmsg(), ...
- select(), epoll_wait(), poll(), ...

So if you have 6 applicaton threads which use epoll() as their main loop so there is a high chance that your'll see 600% CPU (6 cores).

**Comment by nijinboc** [comment] 2015-10-14 14:51
HI, I found that the value m_ready_conn_cnt is not zero (sometime seems very large number) that causes this piece of code in int sockinfo_tcp::rx_wait_helper(int &poll_count, bool is_blocking)

if (!m_n_rx_pkt_ready_list_count && !m_ready_conn_cnt)
	{
		going_to_sleep();
		unlock_tcp_con();
	}
	else
	{
		unlock_tcp_con();
		return 0;
	}

never going_to_sleep();

**Comment by orkmellanox** [comment] 2015-10-14 14:59
it seems you are correct!
thanks for catching this.
the m_ready_conn_cnt was not initialized to 0 in the constructor, so it got random high numbers for non-listen (connected) sockets.

but this actually seem to affect the recv() call and not the epoll_wait() call.
am i missing something?

**Comment by nijinboc** [comment] 2015-10-14 15:06
HI, initially I suspect that it is epoll_wait that causes the high CPU.
But after I adding some printf message in code, I found that it is the variable m_ready_conn_cnt that causes the problem.

**Comment by nijinboc** [comment] 2015-10-14 15:06
Sorry for the misleading

**Comment by nijinboc** [comment] 2015-10-14 15:10
But after adding initializing m_ready_conn_cnt in the constructor, seems still has the problem

**Comment by orkmellanox** [comment] 2015-10-14 15:20
by problem you mean 600% cpu?
using gstack, who do you see spining now?

**Comment by nijinboc** [comment] 2015-10-14 15:20
Sorry, my mistake,
After initializing the variable to 0 in constructor, does solve the problem.
Thanks a lot for the help

**Comment by orkmellanox** [comment] 2015-10-14 15:21
thank you!
i updated the repo with the fix.

**Comment by rosenbaumalex** [comment] 2016-06-02 06:39
OrK fixed the issue back in Oct 2015.
closing the ticket...

**Closed by rosenbaumalex** 2016-06-02 06:39 UTC
Labels: bug
