### ISSUE TITLE
regress bug - the lastest version libvma-8.1.7 make the switching of with/without vma failed.

### ISSUE THREAD

**Issue by jiangdong-sun** [Mellanox/libvma#243] opened 2016-11-18 06:01 UTC
OS: Centos 7.1 
OFED: MLNX_OFED_LINUX-3.4-1.0.0.0-rhel7.1-x86_64

Look at as below.
``
$ LD_PRELOAD=libvma.so ./t_echo_server 192.168.10.10 50001
Local listened address: 192.168.10.10:50001
^C

$ LD_PRELOAD= ./t_echo_server 192.168.10.10 50001 
Local listened address: 192.168.10.10:50001
epoll_ctl: epoll_fd add event with lsock,EPOLLIN.: Bad file descriptor

$ LD_PRELOAD=libvma.so ./t_echo_server 192.168.10.10 50001
Local listened address: 192.168.10.10:50001
``
Either for first without vma then with vma.   And it happens also when to switch via editing /etc/libvma.conf

After it's downgraded to MLNX_OFED_LINUX-3.3-1.0.0.0-rhel7.1-x86_64, the issue disappears.
BTW, It's not related to firmware. In my test, even with the latest firmware, but with MLNX_OFED_LINUX-3.3-1.0,  there is no this issue.

**Comment by OphirMunk** [comment] 2016-11-18 10:22
@jiangdong-sun Please add details.
1. What is commit number (SHA) you are referring to in VMA?
2. Please confirm: issue happens without VMA loaded? It is only OFED version dependent. Right?
3. Please share with us the script that recreates this issue (t_echo_server)? Please attach the script.

**Comment by jiangdong-sun** [comment] 2016-11-22 02:41
@OphirMunk 
1. The VMA is from the latest version 3.4-1.0.0.0 which is located on public download: http://www.mellanox.com/page/mlnx_ofed_matrix?mtag=linux_sw_drivers .
    And it's installed with 
  $ ./mlnxofedinstall --with-vma
2. The issue actual is a switching issue: after use with libvma.so, the the same socket cannot use without libvma.so
3. It's a very common test program. I can attach here.
[t_echo_server.cc.gz](https://github.com/Mellanox/libvma/files/605286/t_echo_server.cc.gz)

**Comment by liranoz12** [comment] 2017-01-09 14:15
@jiangdong-sun

This issue seems to be incompatible between libvma and OS regarding epoll_create() method.

OS does not support creating epoll fd's using epoll_create() with size = 0.
libvma epoll_create() implemention calls os.epoll_create(size + 1) - hence, while the size is 0, there is no error. 

**epoll_create manual :**

`EINVAL size is not positive.`

**linux/fs/eventpoll.c source code:**

```
SYSCALL_DEFINE1(epoll_create, int, size)
{
        if (size <= 0)
                return -EINVAL;

        return sys_epoll_create1(0);
}
```

**t_echo_server.cc :**

```
    //ev.events = EPOLLIN|EPOLLOUT|EPOLLET|EPOLLONESHOT;
    epollfd = epoll_create(0);     <------------------------ invalid size
    ev.events = EPOLLIN|EPOLLET;
```

The fix is already merged -> commit Id e25566b

BTW, I also managed to reproduce the issue using MLNX OFED 3.3-1.0.0.0.
Are you sure the issue disappears using this ofed version ?

**Comment by liranoz12** [comment] 2017-01-23 12:16
@jiangdong-sun Any update?

**Comment by NirNitzani** [comment] 2017-01-31 07:48
No new input from @jiangdong-sun.
If issue still exists please open the thread

**Closed by NirNitzani** 2017-01-31 07:48 UTC

**Comment by jiangdong-sun** [comment] 2017-02-07 06:17
@liranoz12 sorry for so late reply. 
Yes, you are right. Thanks!
It looks my parameters use is not suitable.
>>BTW, I also managed to reproduce the issue using MLNX OFED 3.3-1.0.0.0.
I re-tested and also reproduces the issue with MLNX OFED 3.3-1.0.0.0. Perhaps I used different t_echo_server on different servers.
